apiVersion: v1
kind: Service
metadata:
  name: eks-jx-was-service
  labels:
    app: was
spec:
  ports:
  - port: 9043
    name: http-9043
    protocol: TCP
  - port: 9443
    name: http-9443
    protocol: TCP
  type: LoadBalancer
  selector:
        app: was